### ISSUE TITLE
Problems after upgrading to 7.0.0-beta.0

### ISSUE THREAD

**Issue by pulstar** [flutter-form-builder-ecosystem/flutter_form_builder#870]
The DateTimePicker is showing the following error message:

>
>AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: >Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
> - 'Color' is from 'dart:ui'.
>                  color: theme.backgroundColor ?? Colors.white,
>                               ^
>

Form fields are having multiple selection after being tapped:

![image](https://user-images.githubusercontent.com/1308392/132098913-4b02c74a-9123-4a1f-a1e2-fbeede410ca9.png)

**Comment by chiennv97** [comment]
same issue, please help!

**Comment by YouSour** [comment]
i think it just warning , did you add this on your pubspec.yaml :
```
dependency_overrides:
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
```
